# Generated by Django 4.2.3 on 2023-07-28 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_taskcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
